### PR TITLE
Mojo test

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by jberger** [comment]
Only two minor things I would say. First is that the way Mojolicious dist is packaged, only Mojolicious.pm has a version number. Therefore we typically don't have people put explicit dependencies on core packages like Mojo::Base or Test::Mojo but rather on Mojolicious itself.

Second, Mojo::Base used the way it is used in the test won't do anything. In the example I `use Mojo::Base -strict` as a shortcut for strict, warnings etc. I don't know what it does without any import arguments, actually :-P. Anyway, use whatever you want for strict/warnings but as is I don't know that it is doing anything.

**Comment by jberger** [comment]
Looks like the test isn't run by travis though https://travis-ci.org/yanick/Dancer2-Plugin-WebSocket/jobs/482076649

**Comment by yanick** [comment]
Nah. Mojolicious is merely a recommended dependency, so Travis doesn't install it by default. Hmmm... there must be something I can pass to make it install all the dependencies. Lemme check...

**Comment by yanick** [comment]
Boom! https://travis-ci.org/yanick/Dancer2-Plugin-WebSocket/jobs/483173212 \o/

**Pull request merged**
